blank_issues_enabled=false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/honzas83/archivatorium-web-export/discussions
    about: If you have a question or need help please use create a discussion. Only create an issue for bugs or feature requests.
